package com.foresee.ftcsp.order.manual.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;


public class OrdBillDTO implements Serializable {
    /**
     * 主键,账单id
     * 表 : t_ord_bill
     * 对应字段 : bill_id
     */
    private Long billId;

    /**
     * 账单编号
     * 表 : t_ord_bill
     * 对应字段 : bill_code
     */
    private String billCode;

    /**
     * 账单类型（0-全额，1-分期）
     * 表 : t_ord_bill
     * 对应字段 : bill_type
     */
    private Integer billType;

    /**
     * 账单金额
     * 表 : t_ord_bill
     * 对应字段 : bill_amount
     */
    private BigDecimal billAmount;

    /**
     * 支付状态（0-已付，1待付）
     * 表 : t_ord_bill
     * 对应字段 : pay_status
     */
    private Integer payStatus;

    /**
     * 开票状态（0 未开 1 开票中 2 已开 3 红冲）
     * 表 : t_ord_bill
     * 对应字段 : invoice_status
     */
    private Integer invoiceStatus;

    /**
     * 支付限制时间
     * 表 : t_ord_bill
     * 对应字段 : limit_time
     */
    private Date limitTime;

    /**
     * 支付时间
     * 表 : t_ord_bill
     * 对应字段 : pay_time
     */
    private Date payTime;

    /**
     * 订单id
     * 表 : t_ord_bill
     * 对应字段 : order_id
     */
    private Long orderId;

    /**
     * 支付id
     * 表 : t_ord_bill
     * 对应字段 : pay_id
     */
    private Long payId;

    /**
     * 账单开始时间
     * 表 : t_ord_bill
     * 对应字段 : bill_start_time
     */
    private Date billStartTime;

    /**
     * 账单结束时间
     * 表 : t_ord_bill
     * 对应字段 : bill_end_time
     */
    private Date billEndTime;

    /**
     * 创建人
     * 表 : t_ord_bill
     * 对应字段 : create_user
     */
    private String createUser;

    /**
     * 创建时间
     * 表 : t_ord_bill
     * 对应字段 : create_time
     */
    private Date createTime;

    /**
     * 修改人
     * 表 : t_ord_bill
     * 对应字段 : update_user
     */
    private String updateUser;

    /**
     * 修改日期
     * 表 : t_ord_bill
     * 对应字段 : update_time
     */
    private Date updateTime;
    
    /**
     * 商品名称
     * 表 : t_pdt_goods
     * 对应字段 : goods_name
     */
    private String goodsName;
    
    /**
     * 支付时间 
     */
    private String payTimeStr;
    /**
     * 期数
     */
    private Integer periods;

    /**
     * isParent:关联更新发票状态需要查询的字段。
     */
    private Integer isParent;

    /**
     * parentId:关联更新发票状态需要查询的字段。
     */
    private Long parentId;

    /**
     * orderTime:订单时间
     */
    private Date orderTime;
    /**
     * 该账单对应的支付方式
     */
    private Integer payWay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_ord_bill
     *
     * @MBG Generated Thu Aug 17 10:48:48 CST 2017
     */
    private static final long serialVersionUID = 1L;

    public Date getOrderTime() {
        return orderTime;
    }

    public void setOrderTime(Date orderTime) {
        this.orderTime = orderTime;
    }

    /**
     * get method 
     *
     * @return t_ord_bill.bill_id：主键,账单id
     */
    public Long getBillId() {
        return billId;
    }

    /**
     * set method 
     *
     * @param billId  主键,账单id
     */
    public void setBillId(Long billId) {
        this.billId = billId;
    }

    /**
     * get method 
     *
     * @return t_ord_bill.bill_code：账单编号
     */
    public String getBillCode() {
        return billCode;
    }

    /**
     * set method 
     *
     * @param billCode  账单编号
     */
    public void setBillCode(String billCode) {
        this.billCode = billCode == null ? null : billCode.trim();
    }

    /**
     * get method 
     *
     * @return t_ord_bill.bill_type：账单类型（0-全额，1-分期）
     */
    public Integer getBillType() {
        return billType;
    }

    /**
     * set method 
     *
     * @param billType  账单类型（0-全额，1-分期）
     */
    public void setBillType(Integer billType) {
        this.billType = billType;
    }

    /**
     * get method 
     *
     * @return t_ord_bill.bill_amount：账单金额
     */
    public BigDecimal getBillAmount() {
        return billAmount;
    }

    /**
     * set method 
     *
     * @param billAmount  账单金额
     */
    public void setBillAmount(BigDecimal billAmount) {
        this.billAmount = billAmount;
    }

    /**
     * get method 
     *
     * @return t_ord_bill.pay_status：支付状态（0-已付，1待付）
     */
    public Integer getPayStatus() {
        return payStatus;
    }

    /**
     * set method 
     *
     * @param payStatus  支付状态（0-已付，1待付）
     */
    public void setPayStatus(Integer payStatus) {
        this.payStatus = payStatus;
    }

    /**
     * get method 
     *
     * @return t_ord_bill.invoice_status：开票状态（0 未开 1 开票中 2 已开 3 红冲）
     */
    public Integer getInvoiceStatus() {
        return invoiceStatus;
    }

    /**
     * set method 
     *
     * @param invoiceStatus  开票状态（0 未开 1 开票中 2 已开 3 红冲）
     */
    public void setInvoiceStatus(Integer invoiceStatus) {
        this.invoiceStatus = invoiceStatus;
    }

    /**
     * get method 
     *
     * @return t_ord_bill.limit_time：支付限制时间
     */
    public Date getLimitTime() {
        return limitTime;
    }

    /**
     * set method 
     *
     * @param limitTime  支付限制时间
     */
    public void setLimitTime(Date limitTime) {
        this.limitTime = limitTime;
    }

    /**
     * get method 
     *
     * @return t_ord_bill.pay_time：支付时间
     */
    public Date getPayTime() {
        return payTime;
    }

    /**
     * set method 
     *
     * @param payTime  支付时间
     */
    public void setPayTime(Date payTime) {
        this.payTime = payTime;
    }

    /**
     * get method 
     *
     * @return t_ord_bill.order_id：订单id
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * set method 
     *
     * @param orderId  订单id
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * get method 
     *
     * @return t_ord_bill.pay_id：支付id
     */
    public Long getPayId() {
        return payId;
    }

    /**
     * set method 
     *
     * @param payId  支付id
     */
    public void setPayId(Long payId) {
        this.payId = payId;
    }

    /**
     * get method 
     *
     * @return t_ord_bill.bill_start_time：账单开始时间
     */
    public Date getBillStartTime() {
        return billStartTime;
    }

    /**
     * set method 
     *
     * @param billStartTime  账单开始时间
     */
    public void setBillStartTime(Date billStartTime) {
        this.billStartTime = billStartTime;
    }

    /**
     * get method 
     *
     * @return t_ord_bill.bill_end_time：账单结束时间
     */
    public Date getBillEndTime() {
        return billEndTime;
    }

    /**
     * set method 
     *
     * @param billEndTime  账单结束时间
     */
    public void setBillEndTime(Date billEndTime) {
        this.billEndTime = billEndTime;
    }

    /**
     * get method 
     *
     * @return t_ord_bill.create_user：创建人
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * set method 
     *
     * @param createUser  创建人
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * get method 
     *
     * @return t_ord_bill.create_time：创建时间
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * set method 
     *
     * @param createTime  创建时间
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * get method 
     *
     * @return t_ord_bill.update_user：修改人
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * set method 
     *
     * @param updateUser  修改人
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * get method 
     *
     * @return t_ord_bill.update_time：修改日期
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * set method 
     *
     * @param updateTime  修改日期
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public String getGoodsName() {
		return goodsName;
	}

	public void setGoodsName(String goodsName) {
		this.goodsName = goodsName;
	}
		
	public String getPayTimeStr() {
		return payTimeStr;
	}

	public void setPayTimeStr(String payTimeStr) {
		this.payTimeStr = payTimeStr;
	}
	
	public Integer getPeriods() {
		return periods;
	}

	public void setPeriods(Integer periods) {
		this.periods = periods;
	}

    public Integer getIsParent() {
        return isParent;
    }


    public void setIsParent(Integer isParent) {
        this.isParent = isParent;
    }


    public Long getParentId() {
        return parentId;
    }


    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }


    public Integer getPayWay() {
        return payWay;
    }

    public void setPayWay(Integer payWay) {
        this.payWay = payWay;
    }

    /**
     *
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", billId=").append(billId);
        sb.append(", billCode=").append(billCode);
        sb.append(", billType=").append(billType);
        sb.append(", billAmount=").append(billAmount);
        sb.append(", payStatus=").append(payStatus);
        sb.append(", invoiceStatus=").append(invoiceStatus);
        sb.append(", limitTime=").append(limitTime);
        sb.append(", payTime=").append(payTime);
        sb.append(", orderId=").append(orderId);
        sb.append(", payId=").append(payId);
        sb.append(", billStartTime=").append(billStartTime);
        sb.append(", billEndTime=").append(billEndTime);
        sb.append(", createUser=").append(createUser);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateUser=").append(updateUser);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }
}