package com.foresee.ftcsp.order.manual.dto;

import java.io.Serializable;
import java.util.Date;

public class OrdInvoiceDTO implements Serializable {
    /**
     * 主键,发票id
     * 表 : t_ord_invoice
     * 对应字段 : invoice_id
     */
    private Long invoiceId;

    /**
     * 业务流水号
     * 表 : t_ord_invoice
     * 对应字段 : serial_number
     */
    private String serialNumber;

    /**
     * 发票形式（0=电子发票、1=纸质发票）
     * 表 : t_ord_invoice
     * 对应字段 : invoice_formality
     */
    private Integer invoiceFormality;

    /**
     * 发票类型（0=增值税普通发票，1=增值税专用发票）
     * 表 : t_ord_invoice
     * 对应字段 : invoice_type
     */
    private Integer invoiceType;

    /**
     * 开票类型（0=蓝字发票，1=红字发票）
     * 表 : t_ord_invoice
     * 对应字段 : billing_type
     */
    private Integer billingType;

    /**
     * 销售方纳税人识别号
     * 表 : t_ord_invoice
     * 对应字段 : seller_taxpayer_no
     */
    private String sellerTaxpayerNo;

    /**
     * 销售方名称
     * 表 : t_ord_invoice
     * 对应字段 : seller_name
     */
    private String sellerName;

    /**
     * 销售方地址、电话
     * 表 : t_ord_invoice
     * 对应字段 : seller_address_phone
     */
    private String sellerAddressPhone;

    /**
     * 销售方银行账号
     * 表 : t_ord_invoice
     * 对应字段 : seller_bank_card
     */
    private String sellerBankCard;

    /**
     * 购买方纳税人识别号
     * 表 : t_ord_invoice
     * 对应字段 : buyer_taxpayer_no
     */
    private String buyerTaxpayerNo;

    /**
     * 购买方名称
     * 表 : t_ord_invoice
     * 对应字段 : buyer_name
     */
    private String buyerName;

    /**
     * 购买方地址、电话
     * 表 : t_ord_invoice
     * 对应字段 : buyer_address_phone
     */
    private String buyerAddressPhone;

    /**
     * 购买方银行账号
     * 表 : t_ord_invoice
     * 对应字段 : buyer_bank_card
     */
    private String buyerBankCard;

    /**
     * 购买方电子邮箱地址
     * 表 : t_ord_invoice
     * 对应字段 : buyer_email
     */
    private String buyerEmail;

    /**
     * 购买方手机号码
     * 表 : t_ord_invoice
     * 对应字段 : buyer_mobile
     */
    private String buyerMobile;

    /**
     * 开票人
     * 表 : t_ord_invoice
     * 对应字段 : drawer
     */
    private String drawer;

    /**
     * 收款人
     * 表 : t_ord_invoice
     * 对应字段 : payee
     */
    private String payee;

    /**
     * 复核人
     * 表 : t_ord_invoice
     * 对应字段 : reviewer
     */
    private String reviewer;

    /**
     * 原发票代码（红字发票时不能为空）
     * 表 : t_ord_invoice
     * 对应字段 : original_invoice_code
     */
    private String originalInvoiceCode;

    /**
     * 原发票号码（红字发票时不能为空）
     * 表 : t_ord_invoice
     * 对应字段 : original_invoice_no
     */
    private String originalInvoiceNo;

    /**
     * 价税合计；单位：分
     * 表 : t_ord_invoice
     * 对应字段 : total_amount_tax
     */
    private Long totalAmountTax;

    /**
     * 合计金额；单位：分
     * 表 : t_ord_invoice
     * 对应字段 : total_amount
     */
    private Long totalAmount;

    /**
     * 合计税额；单位：分
     * 表 : t_ord_invoice
     * 对应字段 : total_tax
     */
    private Long totalTax;

    /**
     * 调用状态（0=不调用；1=未调用；2=已调用；3=调用失败；4=调用失败后重新调用成功）
     * 表 : t_ord_invoice
     * 对应字段 : call_status
     */
    private Integer callStatus;

    /**
     * 调用次数
     * 表 : t_ord_invoice
     * 对应字段 : call_number
     */
    private Integer callNumber;

    /**
     * 创建人
     * 表 : t_ord_invoice
     * 对应字段 : create_user
     */
    private String createUser;

    /**
     * 创建时间
     * 表 : t_ord_invoice
     * 对应字段 : create_time
     */
    private Date createTime;

    /**
     * 修改人
     * 表 : t_ord_invoice
     * 对应字段 : update_user
     */
    private String updateUser;

    /**
     * 修改日期
     * 表 : t_ord_invoice
     * 对应字段 : update_time
     */
    private Date updateTime;
    
    /**
     * 修改人
     * 表 : t_ord_invoice
     * 对应字段 : error_code
     */
    private String errorCode;
    
    /**
     * 修改人
     * 表 : t_ord_invoice
     * 对应字段 : error_message
     */
    private String errorMessage;
    
    /**
     * 购买方类型0 个人 1 单位
     * 表 : t_ord_invoice
     * 对应字段 : buyer_type 
     */
    private Integer buyerType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_ord_invoice
     *
     * @MBG Generated Thu Aug 17 10:48:48 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * get method 
     *
     * @return t_ord_invoice.invoice_id：主键,发票id
     */
    public Long getInvoiceId() {
        return invoiceId;
    }

    /**
     * set method 
     *
     * @param invoiceId  主键,发票id
     */
    public void setInvoiceId(Long invoiceId) {
        this.invoiceId = invoiceId;
    }

    /**
     * get method 
     *
     * @return t_ord_invoice.serial_number：业务流水号
     */
    public String getSerialNumber() {
        return serialNumber;
    }

    /**
     * set method 
     *
     * @param serialNumber  业务流水号
     */
    public void setSerialNumber(String serialNumber) {
        this.serialNumber = serialNumber == null ? null : serialNumber.trim();
    }

    /**
     * get method 
     *
     * @return t_ord_invoice.invoice_formality：发票形式（0=电子发票、1=纸质发票）
     */
    public Integer getInvoiceFormality() {
        return invoiceFormality;
    }

    /**
     * set method 
     *
     * @param invoiceFormality  发票形式（0=电子发票、1=纸质发票）
     */
    public void setInvoiceFormality(Integer invoiceFormality) {
        this.invoiceFormality = invoiceFormality;
    }

    /**
     * get method 
     *
     * @return t_ord_invoice.invoice_type：发票类型（0=增值税普通发票，1=增值税专用发票）
     */
    public Integer getInvoiceType() {
        return invoiceType;
    }

    /**
     * set method 
     *
     * @param invoiceType  发票类型（0=增值税普通发票，1=增值税专用发票）
     */
    public void setInvoiceType(Integer invoiceType) {
        this.invoiceType = invoiceType;
    }

    /**
     * get method 
     *
     * @return t_ord_invoice.billing_type：开票类型（0=蓝字发票，1=红字发票）
     */
    public Integer getBillingType() {
        return billingType;
    }

    /**
     * set method 
     *
     * @param billingType  开票类型（0=蓝字发票，1=红字发票）
     */
    public void setBillingType(Integer billingType) {
        this.billingType = billingType;
    }

    /**
     * get method 
     *
     * @return t_ord_invoice.seller_taxpayer_no：销售方纳税人识别号
     */
    public String getSellerTaxpayerNo() {
        return sellerTaxpayerNo;
    }

    /**
     * set method 
     *
     * @param sellerTaxpayerNo  销售方纳税人识别号
     */
    public void setSellerTaxpayerNo(String sellerTaxpayerNo) {
        this.sellerTaxpayerNo = sellerTaxpayerNo == null ? null : sellerTaxpayerNo.trim();
    }

    /**
     * get method 
     *
     * @return t_ord_invoice.seller_name：销售方名称
     */
    public String getSellerName() {
        return sellerName;
    }

    /**
     * set method 
     *
     * @param sellerName  销售方名称
     */
    public void setSellerName(String sellerName) {
        this.sellerName = sellerName == null ? null : sellerName.trim();
    }

    /**
     * get method 
     *
     * @return t_ord_invoice.seller_address_phone：销售方地址、电话
     */
    public String getSellerAddressPhone() {
        return sellerAddressPhone;
    }

    /**
     * set method 
     *
     * @param sellerAddressPhone  销售方地址、电话
     */
    public void setSellerAddressPhone(String sellerAddressPhone) {
        this.sellerAddressPhone = sellerAddressPhone == null ? null : sellerAddressPhone.trim();
    }

    /**
     * get method 
     *
     * @return t_ord_invoice.seller_bank_card：销售方银行账号
     */
    public String getSellerBankCard() {
        return sellerBankCard;
    }

    /**
     * set method 
     *
     * @param sellerBankCard  销售方银行账号
     */
    public void setSellerBankCard(String sellerBankCard) {
        this.sellerBankCard = sellerBankCard == null ? null : sellerBankCard.trim();
    }

    /**
     * get method 
     *
     * @return t_ord_invoice.buyer_taxpayer_no：购买方纳税人识别号
     */
    public String getBuyerTaxpayerNo() {
        return buyerTaxpayerNo;
    }

    /**
     * set method 
     *
     * @param buyerTaxpayerNo  购买方纳税人识别号
     */
    public void setBuyerTaxpayerNo(String buyerTaxpayerNo) {
        this.buyerTaxpayerNo = buyerTaxpayerNo == null ? null : buyerTaxpayerNo.trim();
    }

    /**
     * get method 
     *
     * @return t_ord_invoice.buyer_name：购买方名称
     */
    public String getBuyerName() {
        return buyerName;
    }

    /**
     * set method 
     *
     * @param buyerName  购买方名称
     */
    public void setBuyerName(String buyerName) {
        this.buyerName = buyerName == null ? null : buyerName.trim();
    }

    /**
     * get method 
     *
     * @return t_ord_invoice.buyer_address_phone：购买方地址、电话
     */
    public String getBuyerAddressPhone() {
        return buyerAddressPhone;
    }

    /**
     * set method 
     *
     * @param buyerAddressPhone  购买方地址、电话
     */
    public void setBuyerAddressPhone(String buyerAddressPhone) {
        this.buyerAddressPhone = buyerAddressPhone == null ? null : buyerAddressPhone.trim();
    }

    /**
     * get method 
     *
     * @return t_ord_invoice.buyer_bank_card：购买方银行账号
     */
    public String getBuyerBankCard() {
        return buyerBankCard;
    }

    /**
     * set method 
     *
     * @param buyerBankCard  购买方银行账号
     */
    public void setBuyerBankCard(String buyerBankCard) {
        this.buyerBankCard = buyerBankCard == null ? null : buyerBankCard.trim();
    }

    /**
     * get method 
     *
     * @return t_ord_invoice.buyer_email：购买方电子邮箱地址
     */
    public String getBuyerEmail() {
        return buyerEmail;
    }

    /**
     * set method 
     *
     * @param buyerEmail  购买方电子邮箱地址
     */
    public void setBuyerEmail(String buyerEmail) {
        this.buyerEmail = buyerEmail == null ? null : buyerEmail.trim();
    }

    /**
     * get method 
     *
     * @return t_ord_invoice.buyer_mobile：购买方手机号码
     */
    public String getBuyerMobile() {
        return buyerMobile;
    }

    /**
     * set method 
     *
     * @param buyerMobile  购买方手机号码
     */
    public void setBuyerMobile(String buyerMobile) {
        this.buyerMobile = buyerMobile == null ? null : buyerMobile.trim();
    }

    /**
     * get method 
     *
     * @return t_ord_invoice.drawer：开票人
     */
    public String getDrawer() {
        return drawer;
    }

    /**
     * set method 
     *
     * @param drawer  开票人
     */
    public void setDrawer(String drawer) {
        this.drawer = drawer == null ? null : drawer.trim();
    }

    /**
     * get method 
     *
     * @return t_ord_invoice.payee：收款人
     */
    public String getPayee() {
        return payee;
    }

    /**
     * set method 
     *
     * @param payee  收款人
     */
    public void setPayee(String payee) {
        this.payee = payee == null ? null : payee.trim();
    }

    /**
     * get method 
     *
     * @return t_ord_invoice.reviewer：复核人
     */
    public String getReviewer() {
        return reviewer;
    }

    /**
     * set method 
     *
     * @param reviewer  复核人
     */
    public void setReviewer(String reviewer) {
        this.reviewer = reviewer == null ? null : reviewer.trim();
    }

    /**
     * get method 
     *
     * @return t_ord_invoice.original_invoice_code：原发票代码（红字发票时不能为空）
     */
    public String getOriginalInvoiceCode() {
        return originalInvoiceCode;
    }

    /**
     * set method 
     *
     * @param originalInvoiceCode  原发票代码（红字发票时不能为空）
     */
    public void setOriginalInvoiceCode(String originalInvoiceCode) {
        this.originalInvoiceCode = originalInvoiceCode == null ? null : originalInvoiceCode.trim();
    }

    /**
     * get method 
     *
     * @return t_ord_invoice.original_invoice_no：原发票号码（红字发票时不能为空）
     */
    public String getOriginalInvoiceNo() {
        return originalInvoiceNo;
    }

    /**
     * set method 
     *
     * @param originalInvoiceNo  原发票号码（红字发票时不能为空）
     */
    public void setOriginalInvoiceNo(String originalInvoiceNo) {
        this.originalInvoiceNo = originalInvoiceNo == null ? null : originalInvoiceNo.trim();
    }

    /**
     * get method 
     *
     * @return t_ord_invoice.total_amount_tax：价税合计；单位：分
     */
    public Long getTotalAmountTax() {
        return totalAmountTax;
    }

    /**
     * set method 
     *
     * @param totalAmountTax  价税合计；单位：分
     */
    public void setTotalAmountTax(Long totalAmountTax) {
        this.totalAmountTax = totalAmountTax;
    }

    /**
     * get method 
     *
     * @return t_ord_invoice.total_amount：合计金额；单位：分
     */
    public Long getTotalAmount() {
        return totalAmount;
    }

    /**
     * set method 
     *
     * @param totalAmount  合计金额；单位：分
     */
    public void setTotalAmount(Long totalAmount) {
        this.totalAmount = totalAmount;
    }

    /**
     * get method 
     *
     * @return t_ord_invoice.total_tax：合计税额；单位：分
     */
    public Long getTotalTax() {
        return totalTax;
    }

    /**
     * set method 
     *
     * @param totalTax  合计税额；单位：分
     */
    public void setTotalTax(Long totalTax) {
        this.totalTax = totalTax;
    }

    /**
     * get method 
     *
     * @return t_ord_invoice.call_status：调用状态（0=不调用；1=未调用；2=已调用；3=调用失败；4=调用失败后重新调用成功）
     */
    public Integer getCallStatus() {
        return callStatus;
    }

    /**
     * set method 
     *
     * @param callStatus  调用状态（0=不调用；1=未调用；2=已调用；3=调用失败；4=调用失败后重新调用成功）
     */
    public void setCallStatus(Integer callStatus) {
        this.callStatus = callStatus;
    }

    /**
     * get method 
     *
     * @return t_ord_invoice.call_number：调用次数
     */
    public Integer getCallNumber() {
        return callNumber;
    }

    /**
     * set method 
     *
     * @param callNumber  调用次数
     */
    public void setCallNumber(Integer callNumber) {
        this.callNumber = callNumber;
    }

    /**
     * get method 
     *
     * @return t_ord_invoice.create_user：创建人
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * set method 
     *
     * @param createUser  创建人
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * get method 
     *
     * @return t_ord_invoice.create_time：创建时间
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * set method 
     *
     * @param createTime  创建时间
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * get method 
     *
     * @return t_ord_invoice.update_user：修改人
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * set method 
     *
     * @param updateUser  修改人
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * get method 
     *
     * @return t_ord_invoice.update_time：修改日期
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * set method 
     *
     * @param updateTime  修改日期
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
    
    

    
    public String getErrorCode() {
        return errorCode;
    }

    
    public void setErrorCode(String errorCode) {
        this.errorCode = errorCode;
    }

    
    public String getErrorMessage() {
        return errorMessage;
    }

    
    public void setErrorMessage(String errorMessage) {
        this.errorMessage = errorMessage;
    }
    
    
    public Integer getBuyerType() {
        return buyerType;
    }

    
    public void setBuyerType(Integer buyerType) {
        this.buyerType = buyerType;
    }

    /**
     *
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", invoiceId=").append(invoiceId);
        sb.append(", serialNumber=").append(serialNumber);
        sb.append(", invoiceFormality=").append(invoiceFormality);
        sb.append(", invoiceType=").append(invoiceType);
        sb.append(", billingType=").append(billingType);
        sb.append(", sellerTaxpayerNo=").append(sellerTaxpayerNo);
        sb.append(", sellerName=").append(sellerName);
        sb.append(", sellerAddressPhone=").append(sellerAddressPhone);
        sb.append(", sellerBankCard=").append(sellerBankCard);
        sb.append(", buyerTaxpayerNo=").append(buyerTaxpayerNo);
        sb.append(", buyerName=").append(buyerName);
        sb.append(", buyerAddressPhone=").append(buyerAddressPhone);
        sb.append(", buyerBankCard=").append(buyerBankCard);
        sb.append(", buyerEmail=").append(buyerEmail);
        sb.append(", buyerMobile=").append(buyerMobile);
        sb.append(", drawer=").append(drawer);
        sb.append(", payee=").append(payee);
        sb.append(", reviewer=").append(reviewer);
        sb.append(", originalInvoiceCode=").append(originalInvoiceCode);
        sb.append(", originalInvoiceNo=").append(originalInvoiceNo);
        sb.append(", totalAmountTax=").append(totalAmountTax);
        sb.append(", totalAmount=").append(totalAmount);
        sb.append(", totalTax=").append(totalTax);
        sb.append(", callStatus=").append(callStatus);
        sb.append(", callNumber=").append(callNumber);
        sb.append(", createUser=").append(createUser);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateUser=").append(updateUser);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }
}