package com.foresee.ftcsp.order.manual.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class OrdPayFlowingDTO implements Serializable {
    /**
     * 主键,支付id
     * 表 : t_ord_pay_flowing
     * 对应字段 : pay_id
     */
    private Long payId;

    /**
     * 支付流水
     * 表 : t_ord_pay_flowing
     * 对应字段 : pay_no
     */
    private String payNo;

    /**
     * 支付状态（0 待支付 1支付成功 2支付失败）
     * 表 : t_ord_pay_flowing
     * 对应字段 : pay_state
     */
    private Integer payState;

    /**
     * 支付方式（0-支付宝，1-微信支付，2-银联支付，3-现金）
     * 表 : t_ord_pay_flowing
     * 对应字段 : pay_way
     */
    private Integer payWay;

    /**
     * 第三方支付流水号
     * 表 : t_ord_pay_flowing
     * 对应字段 : three_party_no
     */
    private String threePartyNo;

    /**
     * 支付时间
     * 表 : t_ord_pay_flowing
     * 对应字段 : pay_time
     */
    private Date payTime;

    /**
     * 支付金额
     * 表 : t_ord_pay_flowing
     * 对应字段 : pay_amount
     */
    private BigDecimal payAmount;

    /**
     * 付款方
     * 表 : t_ord_pay_flowing
     * 对应字段 : payer
     */
    private String payer;

    /**
     * 付款方账号
     * 表 : t_ord_pay_flowing
     * 对应字段 : payer_account
     */
    private String payerAccount;

    /**
     * 付款方联系方式
     * 表 : t_ord_pay_flowing
     * 对应字段 : payer_phone
     */
    private String payerPhone;

    /**
     * 收款方
     * 表 : t_ord_pay_flowing
     * 对应字段 : receipt_side
     */
    private String receiptSide;

    /**
     * 收款账号
     * 表 : t_ord_pay_flowing
     * 对应字段 : receipt_account
     */
    private String receiptAccount;

    /**
     * 创建人
     * 表 : t_ord_pay_flowing
     * 对应字段 : create_user
     */
    private String createUser;

    /**
     * 创建时间
     * 表 : t_ord_pay_flowing
     * 对应字段 : create_time
     */
    private Date createTime;

    /**
     * 修改人
     * 表 : t_ord_pay_flowing
     * 对应字段 : update_user
     */
    private String updateUser;

    /**
     * 修改日期
     * 表 : t_ord_pay_flowing
     * 对应字段 : update_time
     */
    private Date updateTime;

    /**
     * 支付APPID
     * 表 : t_ord_pay_flowing
     * 对应字段 : pay_app_id
     */
    private String payAppId;
    
    /**
     * orderId:订单ID。
     */
    private Long orderId;
    
    /**
     * orderCode:订单编码。
     */
    private String orderCode;
    
    /**
     * 服务期限值
     */
    private int serviceTermValue;
    
    /**
     * 服务期限单位0 天 1 月 2 年
     */
    private int serviceTermUnit;
    
    /**
     * 服务开始日期
     */
    private Date serviceStartDate;
    
    /**
     * 服务结束日期
     */
    private Date serviceEndDate;
    
    /**
     * 开通方式。
     */
    private int openingMode;
    
    /**
     * appId:应用Id。
     */
    private String appId;
    
    /**
     * 是否父订单。
     */
    private String isParent;
    
    /**
     * 服务方式。
     */
    private int serviceMode;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_ord_pay_flowing
     *
     * @MBG Generated Thu Aug 17 10:48:48 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * get method 
     *
     * @return t_ord_pay_flowing.pay_id：主键,支付id
     */
    public Long getPayId() {
        return payId;
    }

    /**
     * set method 
     *
     * @param payId  主键,支付id
     */
    public void setPayId(Long payId) {
        this.payId = payId;
    }

    /**
     * get method 
     *
     * @return t_ord_pay_flowing.pay_no：支付流水
     */
    public String getPayNo() {
        return payNo;
    }

    /**
     * set method 
     *
     * @param payNo  支付流水
     */
    public void setPayNo(String payNo) {
        this.payNo = payNo == null ? null : payNo.trim();
    }

    /**
     * get method 
     *
     * @return t_ord_pay_flowing.pay_state：支付状态（0 待支付 1支付成功 2支付失败）
     */
    public Integer getPayState() {
        return payState;
    }

    /**
     * set method 
     *
     * @param payState  支付状态（0 待支付 1支付成功 2支付失败）
     */
    public void setPayState(Integer payState) {
        this.payState = payState;
    }

    /**
     * get method 
     *
     * @return t_ord_pay_flowing.pay_way：支付方式（0-支付宝，1-微信支付，2-银联支付，3-现金）
     */
    public Integer getPayWay() {
        return payWay;
    }

    /**
     * set method 
     *
     * @param payWay  支付方式（0-支付宝，1-微信支付，2-银联支付，3-现金）
     */
    public void setPayWay(Integer payWay) {
        this.payWay = payWay;
    }

    /**
     * get method 
     *
     * @return t_ord_pay_flowing.three_party_no：第三方支付流水号
     */
    public String getThreePartyNo() {
        return threePartyNo;
    }

    /**
     * set method 
     *
     * @param threePartyNo  第三方支付流水号
     */
    public void setThreePartyNo(String threePartyNo) {
        this.threePartyNo = threePartyNo == null ? null : threePartyNo.trim();
    }

    /**
     * get method 
     *
     * @return t_ord_pay_flowing.pay_amount：支付金额
     */
    public BigDecimal getPayAmount() {
        return payAmount;
    }

    /**
     * set method 
     *
     * @param payAmount  支付金额
     */
    public void setPayAmount(BigDecimal payAmount) {
        this.payAmount = payAmount;
    }

    /**
     * get method 
     *
     * @return t_ord_pay_flowing.receipt_side：收款方
     */
    public String getReceiptSide() {
        return receiptSide;
    }

    /**
     * set method 
     *
     * @param receiptSide  收款方
     */
    public void setReceiptSide(String receiptSide) {
        this.receiptSide = receiptSide == null ? null : receiptSide.trim();
    }

    /**
     * get method 
     *
     * @return t_ord_pay_flowing.receipt_account：收款账号
     */
    public String getReceiptAccount() {
        return receiptAccount;
    }

    /**
     * set method 
     *
     * @param receiptAccount  收款账号
     */
    public void setReceiptAccount(String receiptAccount) {
        this.receiptAccount = receiptAccount == null ? null : receiptAccount.trim();
    }

    /**
     * get method 
     *
     * @return t_ord_pay_flowing.create_user：创建人
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * set method 
     *
     * @param createUser  创建人
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * get method 
     *
     * @return t_ord_pay_flowing.create_time：创建时间
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * set method 
     *
     * @param createTime  创建时间
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * get method 
     *
     * @return t_ord_pay_flowing.update_user：修改人
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * set method 
     *
     * @param updateUser  修改人
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * get method 
     *
     * @return t_ord_pay_flowing.update_time：修改日期
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * set method 
     *
     * @param updateTime  修改日期
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
    

    
    public Long getOrderId() {
        return orderId;
    }

    
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }
    
    

    
    public String getOrderCode() {
        return orderCode;
    }

    
    public void setOrderCode(String orderCode) {
        this.orderCode = orderCode;
    }
    
    

    
    public int getServiceTermValue() {
        return serviceTermValue;
    }

    
    public void setServiceTermValue(int serviceTermValue) {
        this.serviceTermValue = serviceTermValue;
    }

    
    public int getServiceTermUnit() {
        return serviceTermUnit;
    }

    
    public void setServiceTermUnit(int serviceTermUnit) {
        this.serviceTermUnit = serviceTermUnit;
    }
    
    

    
    public Date getServiceStartDate() {
        return serviceStartDate;
    }

    
    public void setServiceStartDate(Date serviceStartDate) {
        this.serviceStartDate = serviceStartDate;
    }

    
    public Date getServiceEndDate() {
        return serviceEndDate;
    }

    
    public void setServiceEndDate(Date serviceEndDate) {
        this.serviceEndDate = serviceEndDate;
    }
    
    
    public int getOpeningMode() {
        return openingMode;
    }

    
    public void setOpeningMode(int openingMode) {
        this.openingMode = openingMode;
    }

    
    
    public Date getPayTime() {
        return payTime;
    }

    
    public void setPayTime(Date payTime) {
        this.payTime = payTime;
    }
    
    

    
    public String getPayer() {
        return payer;
    }

    
    public void setPayer(String payer) {
        this.payer = payer;
    }

    
    public String getPayerAccount() {
        return payerAccount;
    }

    
    public void setPayerAccount(String payerAccount) {
        this.payerAccount = payerAccount;
    }

    
    public String getPayerPhone() {
        return payerPhone;
    }

    
    public void setPayerPhone(String payerPhone) {
        this.payerPhone = payerPhone;
    }
    
    

    
    public String getAppId() {
        return appId;
    }

    
    public void setAppId(String appId) {
        this.appId = appId;
    }
    
    

    
    
    public int getServiceMode() {
        return serviceMode;
    }

    
    public void setServiceMode(int serviceMode) {
        this.serviceMode = serviceMode;
    }

    public String getIsParent() {
        return isParent;
    }

    
    public void setIsParent(String isParent) {
        this.isParent = isParent;
    }

    public String getPayAppId() {
        return payAppId;
    }

    public void setPayAppId(String payAppId) {
        this.payAppId = payAppId;
    }

    /**
     *
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", payId=").append(payId);
        sb.append(", payNo=").append(payNo);
        sb.append(", payState=").append(payState);
        sb.append(", payWay=").append(payWay);
        sb.append(", threePartyNo=").append(threePartyNo);
        sb.append(", payAmount=").append(payAmount);
        sb.append(", receiptSide=").append(receiptSide);
        sb.append(", receiptAccount=").append(receiptAccount);
        sb.append(", createUser=").append(createUser);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateUser=").append(updateUser);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }
}