package com.foresee.ftcsp.order.auto.model;

import java.io.Serializable;
import java.util.Date;

public class OrdBillInvoiceRel implements Serializable {
    /**
     * 主键
     * 表 : t_ord_bill_invoice_rel
     * 对应字段 : bill_invoice_rel_id
     */
    private Long billInvoiceRelId;

    /**
     * 账单id
     * 表 : t_ord_bill_invoice_rel
     * 对应字段 : bill_id
     */
    private Long billId;

    /**
     * 电子发票id
     * 表 : t_ord_bill_invoice_rel
     * 对应字段 : invoice_id
     */
    private Long invoiceId;

    /**
     * 创建人
     * 表 : t_ord_bill_invoice_rel
     * 对应字段 : create_user
     */
    private String createUser;

    /**
     * 创建时间
     * 表 : t_ord_bill_invoice_rel
     * 对应字段 : create_time
     */
    private Date createTime;

    /**
     * 修改人
     * 表 : t_ord_bill_invoice_rel
     * 对应字段 : update_user
     */
    private String updateUser;

    /**
     * 修改日期
     * 表 : t_ord_bill_invoice_rel
     * 对应字段 : update_time
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_ord_bill_invoice_rel
     *
     * @MBG Generated Thu Nov 23 09:59:30 GMT+08:00 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * get method 
     *
     * @return t_ord_bill_invoice_rel.bill_invoice_rel_id：主键
     */
    public Long getBillInvoiceRelId() {
        return billInvoiceRelId;
    }

    /**
     * set method 
     *
     * @param billInvoiceRelId  主键
     */
    public void setBillInvoiceRelId(Long billInvoiceRelId) {
        this.billInvoiceRelId = billInvoiceRelId;
    }

    /**
     * get method 
     *
     * @return t_ord_bill_invoice_rel.bill_id：账单id
     */
    public Long getBillId() {
        return billId;
    }

    /**
     * set method 
     *
     * @param billId  账单id
     */
    public void setBillId(Long billId) {
        this.billId = billId;
    }

    /**
     * get method 
     *
     * @return t_ord_bill_invoice_rel.invoice_id：电子发票id
     */
    public Long getInvoiceId() {
        return invoiceId;
    }

    /**
     * set method 
     *
     * @param invoiceId  电子发票id
     */
    public void setInvoiceId(Long invoiceId) {
        this.invoiceId = invoiceId;
    }

    /**
     * get method 
     *
     * @return t_ord_bill_invoice_rel.create_user：创建人
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * set method 
     *
     * @param createUser  创建人
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * get method 
     *
     * @return t_ord_bill_invoice_rel.create_time：创建时间
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * set method 
     *
     * @param createTime  创建时间
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * get method 
     *
     * @return t_ord_bill_invoice_rel.update_user：修改人
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * set method 
     *
     * @param updateUser  修改人
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * get method 
     *
     * @return t_ord_bill_invoice_rel.update_time：修改日期
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * set method 
     *
     * @param updateTime  修改日期
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     *
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", billInvoiceRelId=").append(billInvoiceRelId);
        sb.append(", billId=").append(billId);
        sb.append(", invoiceId=").append(invoiceId);
        sb.append(", createUser=").append(createUser);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateUser=").append(updateUser);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }
}