package com.foresee.ftcsp.order.auto.model;

import java.io.Serializable;
import java.util.Date;

public class OrdBillingInfo implements Serializable {
    /**
     * 开票信息id
     * 表 : t_ord_billing_info
     * 对应字段 : billing_info_id
     */
    private Long billingInfoId;

    /**
     * 购买方类型0 个人 1 单位
     * 表 : t_ord_billing_info
     * 对应字段 : buyer_type
     */
    private Integer buyerType;

    /**
     * 购买方纳税人识别号
     * 表 : t_ord_billing_info
     * 对应字段 : buyer_taxpayer_no
     */
    private String buyerTaxpayerNo;

    /**
     * 购买方名称
     * 表 : t_ord_billing_info
     * 对应字段 : buyer_name
     */
    private String buyerName;

    /**
     * 购买方地址、电话
     * 表 : t_ord_billing_info
     * 对应字段 : buyer_address_phone
     */
    private String buyerAddressPhone;

    /**
     * 购买方银行账号
     * 表 : t_ord_billing_info
     * 对应字段 : buyer_bank_card
     */
    private String buyerBankCard;

    /**
     * 购买方电子邮箱地址
     * 表 : t_ord_billing_info
     * 对应字段 : buyer_email
     */
    private String buyerEmail;

    /**
     * 购买方手机号码
     * 表 : t_ord_billing_info
     * 对应字段 : buyer_mobile
     */
    private String buyerMobile;

    /**
     * 创建人
     * 表 : t_ord_billing_info
     * 对应字段 : create_user
     */
    private String createUser;

    /**
     * 创建时间
     * 表 : t_ord_billing_info
     * 对应字段 : create_time
     */
    private Date createTime;

    /**
     * 修改人
     * 表 : t_ord_billing_info
     * 对应字段 : update_user
     */
    private String updateUser;

    /**
     * 修改时间
     * 表 : t_ord_billing_info
     * 对应字段 : update_time
     */
    private Date updateTime;

    /**
     * 开户行名称
     * 表 : t_ord_billing_info
     * 对应字段 : bank_name
     */
    private String bankName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_ord_billing_info
     *
     * @MBG Generated Thu Dec 14 18:48:59 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * get method 
     *
     * @return t_ord_billing_info.billing_info_id：开票信息id
     */
    public Long getBillingInfoId() {
        return billingInfoId;
    }

    /**
     * set method 
     *
     * @param billingInfoId  开票信息id
     */
    public void setBillingInfoId(Long billingInfoId) {
        this.billingInfoId = billingInfoId;
    }

    /**
     * get method 
     *
     * @return t_ord_billing_info.buyer_type：购买方类型0 个人 1 单位
     */
    public Integer getBuyerType() {
        return buyerType;
    }

    /**
     * set method 
     *
     * @param buyerType  购买方类型0 个人 1 单位
     */
    public void setBuyerType(Integer buyerType) {
        this.buyerType = buyerType;
    }

    /**
     * get method 
     *
     * @return t_ord_billing_info.buyer_taxpayer_no：购买方纳税人识别号
     */
    public String getBuyerTaxpayerNo() {
        return buyerTaxpayerNo;
    }

    /**
     * set method 
     *
     * @param buyerTaxpayerNo  购买方纳税人识别号
     */
    public void setBuyerTaxpayerNo(String buyerTaxpayerNo) {
        this.buyerTaxpayerNo = buyerTaxpayerNo == null ? null : buyerTaxpayerNo.trim();
    }

    /**
     * get method 
     *
     * @return t_ord_billing_info.buyer_name：购买方名称
     */
    public String getBuyerName() {
        return buyerName;
    }

    /**
     * set method 
     *
     * @param buyerName  购买方名称
     */
    public void setBuyerName(String buyerName) {
        this.buyerName = buyerName == null ? null : buyerName.trim();
    }

    /**
     * get method 
     *
     * @return t_ord_billing_info.buyer_address_phone：购买方地址、电话
     */
    public String getBuyerAddressPhone() {
        return buyerAddressPhone;
    }

    /**
     * set method 
     *
     * @param buyerAddressPhone  购买方地址、电话
     */
    public void setBuyerAddressPhone(String buyerAddressPhone) {
        this.buyerAddressPhone = buyerAddressPhone == null ? null : buyerAddressPhone.trim();
    }

    /**
     * get method 
     *
     * @return t_ord_billing_info.buyer_bank_card：购买方银行账号
     */
    public String getBuyerBankCard() {
        return buyerBankCard;
    }

    /**
     * set method 
     *
     * @param buyerBankCard  购买方银行账号
     */
    public void setBuyerBankCard(String buyerBankCard) {
        this.buyerBankCard = buyerBankCard == null ? null : buyerBankCard.trim();
    }

    /**
     * get method 
     *
     * @return t_ord_billing_info.buyer_email：购买方电子邮箱地址
     */
    public String getBuyerEmail() {
        return buyerEmail;
    }

    /**
     * set method 
     *
     * @param buyerEmail  购买方电子邮箱地址
     */
    public void setBuyerEmail(String buyerEmail) {
        this.buyerEmail = buyerEmail == null ? null : buyerEmail.trim();
    }

    /**
     * get method 
     *
     * @return t_ord_billing_info.buyer_mobile：购买方手机号码
     */
    public String getBuyerMobile() {
        return buyerMobile;
    }

    /**
     * set method 
     *
     * @param buyerMobile  购买方手机号码
     */
    public void setBuyerMobile(String buyerMobile) {
        this.buyerMobile = buyerMobile == null ? null : buyerMobile.trim();
    }

    /**
     * get method 
     *
     * @return t_ord_billing_info.create_user：创建人
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * set method 
     *
     * @param createUser  创建人
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * get method 
     *
     * @return t_ord_billing_info.create_time：创建时间
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * set method 
     *
     * @param createTime  创建时间
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * get method 
     *
     * @return t_ord_billing_info.update_user：修改人
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * set method 
     *
     * @param updateUser  修改人
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * get method 
     *
     * @return t_ord_billing_info.update_time：修改时间
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * set method 
     *
     * @param updateTime  修改时间
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * get method 
     *
     * @return t_ord_billing_info.bank_name：开户行名称
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * set method 
     *
     * @param bankName  开户行名称
     */
    public void setBankName(String bankName) {
        this.bankName = bankName == null ? null : bankName.trim();
    }

    /**
     *
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", billingInfoId=").append(billingInfoId);
        sb.append(", buyerType=").append(buyerType);
        sb.append(", buyerTaxpayerNo=").append(buyerTaxpayerNo);
        sb.append(", buyerName=").append(buyerName);
        sb.append(", buyerAddressPhone=").append(buyerAddressPhone);
        sb.append(", buyerBankCard=").append(buyerBankCard);
        sb.append(", buyerEmail=").append(buyerEmail);
        sb.append(", buyerMobile=").append(buyerMobile);
        sb.append(", createUser=").append(createUser);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateUser=").append(updateUser);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", bankName=").append(bankName);
        sb.append("]");
        return sb.toString();
    }
}