package com.foresee.ftcsp.order.auto.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class OrdBillItem implements Serializable {
    /**
     * 主键
     * 表 : t_ord_bill_item
     * 对应字段 : bill_item_id
     */
    private Long billItemId;

    /**
     * 账单id
     * 表 : t_ord_bill_item
     * 对应字段 : bill_id
     */
    private Long billId;

    /**
     * 0 正常行 1 优惠行
     * 表 : t_ord_bill_item
     * 对应字段 : item_type
     */
    private Integer itemType;

    /**
     * 项目名称
     * 表 : t_ord_bill_item
     * 对应字段 : item_name
     */
    private String itemName;

    /**
     * 项目代码
     * 表 : t_ord_bill_item
     * 对应字段 : item_code
     */
    private String itemCode;

    /**
     * 计量单位
     * 表 : t_ord_bill_item
     * 对应字段 : unit
     */
    private String unit;

    /**
     * 规格型号
     * 表 : t_ord_bill_item
     * 对应字段 : spec
     */
    private String spec;

    /**
     * 项目数量（整数）
     * 表 : t_ord_bill_item
     * 对应字段 : qty
     */
    private Integer qty;

    /**
     * 项目单价
     * 表 : t_ord_bill_item
     * 对应字段 : price
     */
    private BigDecimal price;

    /**
     * 项目金额
     * 表 : t_ord_bill_item
     * 对应字段 : amount
     */
    private BigDecimal amount;

    /**
     * 税率（最高2位小数）
     * 表 : t_ord_bill_item
     * 对应字段 : tax_rate
     */
    private BigDecimal taxRate;

    /**
     * 创建人
     * 表 : t_ord_bill_item
     * 对应字段 : create_user
     */
    private String createUser;

    /**
     * 创建时间
     * 表 : t_ord_bill_item
     * 对应字段 : create_time
     */
    private Date createTime;

    /**
     * 修改人
     * 表 : t_ord_bill_item
     * 对应字段 : update_user
     */
    private String updateUser;

    /**
     * 修改日期
     * 表 : t_ord_bill_item
     * 对应字段 : update_time
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_ord_bill_item
     *
     * @MBG Generated Wed Nov 22 10:21:12 GMT+08:00 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * get method 
     *
     * @return t_ord_bill_item.bill_item_id：主键
     */
    public Long getBillItemId() {
        return billItemId;
    }

    /**
     * set method 
     *
     * @param billItemId  主键
     */
    public void setBillItemId(Long billItemId) {
        this.billItemId = billItemId;
    }

    /**
     * get method 
     *
     * @return t_ord_bill_item.bill_id：账单id
     */
    public Long getBillId() {
        return billId;
    }

    /**
     * set method 
     *
     * @param billId  账单id
     */
    public void setBillId(Long billId) {
        this.billId = billId;
    }

    /**
     * get method 
     *
     * @return t_ord_bill_item.item_type：0 正常行 1 优惠行
     */
    public Integer getItemType() {
        return itemType;
    }

    /**
     * set method 
     *
     * @param itemType  0 正常行 1 优惠行
     */
    public void setItemType(Integer itemType) {
        this.itemType = itemType;
    }

    /**
     * get method 
     *
     * @return t_ord_bill_item.item_name：项目名称
     */
    public String getItemName() {
        return itemName;
    }

    /**
     * set method 
     *
     * @param itemName  项目名称
     */
    public void setItemName(String itemName) {
        this.itemName = itemName == null ? null : itemName.trim();
    }

    /**
     * get method 
     *
     * @return t_ord_bill_item.item_code：项目代码
     */
    public String getItemCode() {
        return itemCode;
    }

    /**
     * set method 
     *
     * @param itemCode  项目代码
     */
    public void setItemCode(String itemCode) {
        this.itemCode = itemCode == null ? null : itemCode.trim();
    }

    /**
     * get method 
     *
     * @return t_ord_bill_item.unit：计量单位
     */
    public String getUnit() {
        return unit;
    }

    /**
     * set method 
     *
     * @param unit  计量单位
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * get method 
     *
     * @return t_ord_bill_item.spec：规格型号
     */
    public String getSpec() {
        return spec;
    }

    /**
     * set method 
     *
     * @param spec  规格型号
     */
    public void setSpec(String spec) {
        this.spec = spec == null ? null : spec.trim();
    }

    /**
     * get method 
     *
     * @return t_ord_bill_item.qty：项目数量（整数）
     */
    public Integer getQty() {
        return qty;
    }

    /**
     * set method 
     *
     * @param qty  项目数量（整数）
     */
    public void setQty(Integer qty) {
        this.qty = qty;
    }

    /**
     * get method 
     *
     * @return t_ord_bill_item.price：项目单价
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * set method 
     *
     * @param price  项目单价
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * get method 
     *
     * @return t_ord_bill_item.amount：项目金额
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * set method 
     *
     * @param amount  项目金额
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * get method 
     *
     * @return t_ord_bill_item.tax_rate：税率（最高2位小数）
     */
    public BigDecimal getTaxRate() {
        return taxRate;
    }

    /**
     * set method 
     *
     * @param taxRate  税率（最高2位小数）
     */
    public void setTaxRate(BigDecimal taxRate) {
        this.taxRate = taxRate;
    }

    /**
     * get method 
     *
     * @return t_ord_bill_item.create_user：创建人
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * set method 
     *
     * @param createUser  创建人
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * get method 
     *
     * @return t_ord_bill_item.create_time：创建时间
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * set method 
     *
     * @param createTime  创建时间
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * get method 
     *
     * @return t_ord_bill_item.update_user：修改人
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * set method 
     *
     * @param updateUser  修改人
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * get method 
     *
     * @return t_ord_bill_item.update_time：修改日期
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * set method 
     *
     * @param updateTime  修改日期
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     *
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", billItemId=").append(billItemId);
        sb.append(", billId=").append(billId);
        sb.append(", itemType=").append(itemType);
        sb.append(", itemName=").append(itemName);
        sb.append(", itemCode=").append(itemCode);
        sb.append(", unit=").append(unit);
        sb.append(", spec=").append(spec);
        sb.append(", qty=").append(qty);
        sb.append(", price=").append(price);
        sb.append(", amount=").append(amount);
        sb.append(", taxRate=").append(taxRate);
        sb.append(", createUser=").append(createUser);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateUser=").append(updateUser);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }
}