package com.foresee.ftcsp.order.auto.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class OrdDiscountEntry implements Serializable {
    /**
     * 主键
     * 表 : t_ord_discount_entry
     * 对应字段 : order_discount_entry_id
     */
    private Long orderDiscountEntryId;

    /**
     * 订单id
     * 表 : t_ord_discount_entry
     * 对应字段 : order_id
     */
    private Long orderId;

    /**
     * 优惠条目
     * 表 : t_ord_discount_entry
     * 对应字段 : discount_entry
     */
    private String discountEntry;

    /**
     * 优惠金额
     * 表 : t_ord_discount_entry
     * 对应字段 : discount_amount
     */
    private BigDecimal discountAmount;

    /**
     * 说明
     * 表 : t_ord_discount_entry
     * 对应字段 : remark
     */
    private String remark;

    /**
     * 创建人
     * 表 : t_ord_discount_entry
     * 对应字段 : create_user
     */
    private String createUser;

    /**
     * 创建时间
     * 表 : t_ord_discount_entry
     * 对应字段 : create_time
     */
    private Date createTime;

    /**
     * 修改人
     * 表 : t_ord_discount_entry
     * 对应字段 : update_user
     */
    private String updateUser;

    /**
     * 修改日期
     * 表 : t_ord_discount_entry
     * 对应字段 : update_time
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_ord_discount_entry
     *
     * @MBG Generated Thu Aug 17 10:48:48 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * get method 
     *
     * @return t_ord_discount_entry.order_discount_entry_id：主键
     */
    public Long getOrderDiscountEntryId() {
        return orderDiscountEntryId;
    }

    /**
     * set method 
     *
     * @param orderDiscountEntryId  主键
     */
    public void setOrderDiscountEntryId(Long orderDiscountEntryId) {
        this.orderDiscountEntryId = orderDiscountEntryId;
    }

    /**
     * get method 
     *
     * @return t_ord_discount_entry.order_id：订单id
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * set method 
     *
     * @param orderId  订单id
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * get method 
     *
     * @return t_ord_discount_entry.discount_entry：优惠条目
     */
    public String getDiscountEntry() {
        return discountEntry;
    }

    /**
     * set method 
     *
     * @param discountEntry  优惠条目
     */
    public void setDiscountEntry(String discountEntry) {
        this.discountEntry = discountEntry == null ? null : discountEntry.trim();
    }

    /**
     * get method 
     *
     * @return t_ord_discount_entry.discount_amount：优惠金额
     */
    public BigDecimal getDiscountAmount() {
        return discountAmount;
    }

    /**
     * set method 
     *
     * @param discountAmount  优惠金额
     */
    public void setDiscountAmount(BigDecimal discountAmount) {
        this.discountAmount = discountAmount;
    }

    /**
     * get method 
     *
     * @return t_ord_discount_entry.remark：说明
     */
    public String getRemark() {
        return remark;
    }

    /**
     * set method 
     *
     * @param remark  说明
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * get method 
     *
     * @return t_ord_discount_entry.create_user：创建人
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * set method 
     *
     * @param createUser  创建人
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * get method 
     *
     * @return t_ord_discount_entry.create_time：创建时间
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * set method 
     *
     * @param createTime  创建时间
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * get method 
     *
     * @return t_ord_discount_entry.update_user：修改人
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * set method 
     *
     * @param updateUser  修改人
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * get method 
     *
     * @return t_ord_discount_entry.update_time：修改日期
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * set method 
     *
     * @param updateTime  修改日期
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     *
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", orderDiscountEntryId=").append(orderDiscountEntryId);
        sb.append(", orderId=").append(orderId);
        sb.append(", discountEntry=").append(discountEntry);
        sb.append(", discountAmount=").append(discountAmount);
        sb.append(", remark=").append(remark);
        sb.append(", createUser=").append(createUser);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateUser=").append(updateUser);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }
}