package com.foresee.ftcsp.order.auto.model;

import java.io.Serializable;
import java.util.Date;

public class OrdDelivery implements Serializable {
    /**
     * 主键，配送id
     * 表 : t_ord_delivery
     * 对应字段 : delivery_id
     */
    private Long deliveryId;

    /**
     * 订单id
     * 表 : t_ord_delivery
     * 对应字段 : order_id
     */
    private Long orderId;

    /**
     * 配送方式（0-快递，1-上面自提）
     * 表 : t_ord_delivery
     * 对应字段 : delivery_mode
     */
    private Integer deliveryMode;

    /**
     * 收货人
     * 表 : t_ord_delivery
     * 对应字段 : receiver
     */
    private String receiver;

    /**
     * 收货人电话
     * 表 : t_ord_delivery
     * 对应字段 : receiver_phone
     */
    private String receiverPhone;

    /**
     * 收货人地址
     * 表 : t_ord_delivery
     * 对应字段 : receiver_address
     */
    private String receiverAddress;

    /**
     * 自提地址
     * 表 : t_ord_delivery
     * 对应字段 : invite_address
     */
    private String inviteAddress;

    /**
     * 自提时间
     * 表 : t_ord_delivery
     * 对应字段 : invite_time
     */
    private Date inviteTime;

    /**
     * 创建人
     * 表 : t_ord_delivery
     * 对应字段 : create_user
     */
    private String createUser;

    /**
     * 创建时间
     * 表 : t_ord_delivery
     * 对应字段 : create_time
     */
    private Date createTime;

    /**
     * 修改人
     * 表 : t_ord_delivery
     * 对应字段 : update_user
     */
    private String updateUser;

    /**
     * 修改日期
     * 表 : t_ord_delivery
     * 对应字段 : update_time
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_ord_delivery
     *
     * @MBG Generated Thu Aug 17 10:48:48 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * get method 
     *
     * @return t_ord_delivery.delivery_id：主键，配送id
     */
    public Long getDeliveryId() {
        return deliveryId;
    }

    /**
     * set method 
     *
     * @param deliveryId  主键，配送id
     */
    public void setDeliveryId(Long deliveryId) {
        this.deliveryId = deliveryId;
    }

    /**
     * get method 
     *
     * @return t_ord_delivery.order_id：订单id
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * set method 
     *
     * @param orderId  订单id
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * get method 
     *
     * @return t_ord_delivery.delivery_mode：配送方式（0-快递，1-上面自提）
     */
    public Integer getDeliveryMode() {
        return deliveryMode;
    }

    /**
     * set method 
     *
     * @param deliveryMode  配送方式（0-快递，1-上面自提）
     */
    public void setDeliveryMode(Integer deliveryMode) {
        this.deliveryMode = deliveryMode;
    }

    /**
     * get method 
     *
     * @return t_ord_delivery.receiver：收货人
     */
    public String getReceiver() {
        return receiver;
    }

    /**
     * set method 
     *
     * @param receiver  收货人
     */
    public void setReceiver(String receiver) {
        this.receiver = receiver == null ? null : receiver.trim();
    }

    /**
     * get method 
     *
     * @return t_ord_delivery.receiver_phone：收货人电话
     */
    public String getReceiverPhone() {
        return receiverPhone;
    }

    /**
     * set method 
     *
     * @param receiverPhone  收货人电话
     */
    public void setReceiverPhone(String receiverPhone) {
        this.receiverPhone = receiverPhone == null ? null : receiverPhone.trim();
    }

    /**
     * get method 
     *
     * @return t_ord_delivery.receiver_address：收货人地址
     */
    public String getReceiverAddress() {
        return receiverAddress;
    }

    /**
     * set method 
     *
     * @param receiverAddress  收货人地址
     */
    public void setReceiverAddress(String receiverAddress) {
        this.receiverAddress = receiverAddress == null ? null : receiverAddress.trim();
    }

    /**
     * get method 
     *
     * @return t_ord_delivery.invite_address：自提地址
     */
    public String getInviteAddress() {
        return inviteAddress;
    }

    /**
     * set method 
     *
     * @param inviteAddress  自提地址
     */
    public void setInviteAddress(String inviteAddress) {
        this.inviteAddress = inviteAddress == null ? null : inviteAddress.trim();
    }

    /**
     * get method 
     *
     * @return t_ord_delivery.invite_time：自提时间
     */
    public Date getInviteTime() {
        return inviteTime;
    }

    /**
     * set method 
     *
     * @param inviteTime  自提时间
     */
    public void setInviteTime(Date inviteTime) {
        this.inviteTime = inviteTime;
    }

    /**
     * get method 
     *
     * @return t_ord_delivery.create_user：创建人
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * set method 
     *
     * @param createUser  创建人
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * get method 
     *
     * @return t_ord_delivery.create_time：创建时间
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * set method 
     *
     * @param createTime  创建时间
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * get method 
     *
     * @return t_ord_delivery.update_user：修改人
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * set method 
     *
     * @param updateUser  修改人
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * get method 
     *
     * @return t_ord_delivery.update_time：修改日期
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * set method 
     *
     * @param updateTime  修改日期
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     *
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", deliveryId=").append(deliveryId);
        sb.append(", orderId=").append(orderId);
        sb.append(", deliveryMode=").append(deliveryMode);
        sb.append(", receiver=").append(receiver);
        sb.append(", receiverPhone=").append(receiverPhone);
        sb.append(", receiverAddress=").append(receiverAddress);
        sb.append(", inviteAddress=").append(inviteAddress);
        sb.append(", inviteTime=").append(inviteTime);
        sb.append(", createUser=").append(createUser);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateUser=").append(updateUser);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }
}