package com.foresee.ftcsp.order.auto.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class OrdInvoiceExtend implements Serializable {
    /**
     * 主键
     * 表 : t_ord_invoice_extend
     * 对应字段 : invoice_extend_id
     */
    private Long invoiceExtendId;

    /**
     * 发票id
     * 表 : t_ord_invoice_extend
     * 对应字段 : invoice_id
     */
    private Long invoiceId;

    /**
     * 发票代码
     * 表 : t_ord_invoice_extend
     * 对应字段 : invoice_code
     */
    private String invoiceCode;

    /**
     * 发票号码
     * 表 : t_ord_invoice_extend
     * 对应字段 : invoice_number
     */
    private String invoiceNumber;

    /**
     * 开票时间
     * 表 : t_ord_invoice_extend
     * 对应字段 : billing_time
     */
    private Date billingTime;

    /**
     * 发票密文
     * 表 : t_ord_invoice_extend
     * 对应字段 : invoce_ciphertext
     */
    private String invoceCiphertext;

    /**
     * 校验码
     * 表 : t_ord_invoice_extend
     * 对应字段 : validate_code
     */
    private String validateCode;

    /**
     * 下载码
     * 表 : t_ord_invoice_extend
     * 对应字段 : xzm
     */
    private String xzm;

    /**
     * 二维码
     * 表 : t_ord_invoice_extend
     * 对应字段 : qrcode
     */
    private String qrcode;

    /**
     * 返回代码
     * 表 : t_ord_invoice_extend
     * 对应字段 : return_code
     */
    private String returnCode;

    /**
     * 返回消息
     * 表 : t_ord_invoice_extend
     * 对应字段 : return_msg
     */
    private String returnMsg;

    /**
     * 短信通知状态（0=未发送；1=发送中；2=已发送；3=发送失败；4=不发送）
     * 表 : t_ord_invoice_extend
     * 对应字段 : sms_send_flag
     */
    private Integer smsSendFlag;

    /**
     * 短信发送时间
     * 表 : t_ord_invoice_extend
     * 对应字段 : sms_send_date
     */
    private Date smsSendDate;

    /**
     * 短信发送内容
     * 表 : t_ord_invoice_extend
     * 对应字段 : sms_send_content
     */
    private String smsSendContent;

    /**
     * 创建人
     * 表 : t_ord_invoice_extend
     * 对应字段 : create_user
     */
    private String createUser;

    /**
     * 创建时间
     * 表 : t_ord_invoice_extend
     * 对应字段 : create_time
     */
    private Date createTime;

    /**
     * 修改人
     * 表 : t_ord_invoice_extend
     * 对应字段 : update_user
     */
    private String updateUser;

    /**
     * 修改时间
     * 表 : t_ord_invoice_extend
     * 对应字段 : update_time
     */
    private Date updateTime;

    /**
     * 是否红冲作废(0否 1:已红冲)
     * 表 : t_ord_invoice_extend
     * 对应字段 : invalid
     */
    private Integer invalid;

    /**
     * 税控设备编号
     * 表 : t_ord_invoice_extend
     * 对应字段 : device_code
     */
    private String deviceCode;

    /**
     * 备注
     * 表 : t_ord_invoice_extend
     * 对应字段 : remark
     */
    private String remark;

    /**
     * 发票流水号
     * 表 : t_ord_invoice_extend
     * 对应字段 : invoice_flowing_code
     */
    private String invoiceFlowingCode;

    /**
     * 发票金额（含税：元）
     * 表 : t_ord_invoice_extend
     * 对应字段 : invoice_amount
     */
    private BigDecimal invoiceAmount;

    /**
     * 开票类型（0=蓝字发票，1=红字发票）
     * 表 : t_ord_invoice_extend
     * 对应字段 : billing_type
     */
    private Integer billingType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_ord_invoice_extend
     *
     * @MBG Generated Tue Nov 28 16:28:06 GMT+08:00 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * get method 
     *
     * @return t_ord_invoice_extend.invoice_extend_id：主键
     */
    public Long getInvoiceExtendId() {
        return invoiceExtendId;
    }

    /**
     * set method 
     *
     * @param invoiceExtendId  主键
     */
    public void setInvoiceExtendId(Long invoiceExtendId) {
        this.invoiceExtendId = invoiceExtendId;
    }

    /**
     * get method 
     *
     * @return t_ord_invoice_extend.invoice_id：发票id
     */
    public Long getInvoiceId() {
        return invoiceId;
    }

    /**
     * set method 
     *
     * @param invoiceId  发票id
     */
    public void setInvoiceId(Long invoiceId) {
        this.invoiceId = invoiceId;
    }

    /**
     * get method 
     *
     * @return t_ord_invoice_extend.invoice_code：发票代码
     */
    public String getInvoiceCode() {
        return invoiceCode;
    }

    /**
     * set method 
     *
     * @param invoiceCode  发票代码
     */
    public void setInvoiceCode(String invoiceCode) {
        this.invoiceCode = invoiceCode == null ? null : invoiceCode.trim();
    }

    /**
     * get method 
     *
     * @return t_ord_invoice_extend.invoice_number：发票号码
     */
    public String getInvoiceNumber() {
        return invoiceNumber;
    }

    /**
     * set method 
     *
     * @param invoiceNumber  发票号码
     */
    public void setInvoiceNumber(String invoiceNumber) {
        this.invoiceNumber = invoiceNumber == null ? null : invoiceNumber.trim();
    }

    /**
     * get method 
     *
     * @return t_ord_invoice_extend.billing_time：开票时间
     */
    public Date getBillingTime() {
        return billingTime;
    }

    /**
     * set method 
     *
     * @param billingTime  开票时间
     */
    public void setBillingTime(Date billingTime) {
        this.billingTime = billingTime;
    }

    /**
     * get method 
     *
     * @return t_ord_invoice_extend.invoce_ciphertext：发票密文
     */
    public String getInvoceCiphertext() {
        return invoceCiphertext;
    }

    /**
     * set method 
     *
     * @param invoceCiphertext  发票密文
     */
    public void setInvoceCiphertext(String invoceCiphertext) {
        this.invoceCiphertext = invoceCiphertext == null ? null : invoceCiphertext.trim();
    }

    /**
     * get method 
     *
     * @return t_ord_invoice_extend.validate_code：校验码
     */
    public String getValidateCode() {
        return validateCode;
    }

    /**
     * set method 
     *
     * @param validateCode  校验码
     */
    public void setValidateCode(String validateCode) {
        this.validateCode = validateCode == null ? null : validateCode.trim();
    }

    /**
     * get method 
     *
     * @return t_ord_invoice_extend.xzm：下载码
     */
    public String getXzm() {
        return xzm;
    }

    /**
     * set method 
     *
     * @param xzm  下载码
     */
    public void setXzm(String xzm) {
        this.xzm = xzm == null ? null : xzm.trim();
    }

    /**
     * get method 
     *
     * @return t_ord_invoice_extend.qrcode：二维码
     */
    public String getQrcode() {
        return qrcode;
    }

    /**
     * set method 
     *
     * @param qrcode  二维码
     */
    public void setQrcode(String qrcode) {
        this.qrcode = qrcode == null ? null : qrcode.trim();
    }

    /**
     * get method 
     *
     * @return t_ord_invoice_extend.return_code：返回代码
     */
    public String getReturnCode() {
        return returnCode;
    }

    /**
     * set method 
     *
     * @param returnCode  返回代码
     */
    public void setReturnCode(String returnCode) {
        this.returnCode = returnCode == null ? null : returnCode.trim();
    }

    /**
     * get method 
     *
     * @return t_ord_invoice_extend.return_msg：返回消息
     */
    public String getReturnMsg() {
        return returnMsg;
    }

    /**
     * set method 
     *
     * @param returnMsg  返回消息
     */
    public void setReturnMsg(String returnMsg) {
        this.returnMsg = returnMsg == null ? null : returnMsg.trim();
    }

    /**
     * get method 
     *
     * @return t_ord_invoice_extend.sms_send_flag：短信通知状态（0=未发送；1=发送中；2=已发送；3=发送失败；4=不发送）
     */
    public Integer getSmsSendFlag() {
        return smsSendFlag;
    }

    /**
     * set method 
     *
     * @param smsSendFlag  短信通知状态（0=未发送；1=发送中；2=已发送；3=发送失败；4=不发送）
     */
    public void setSmsSendFlag(Integer smsSendFlag) {
        this.smsSendFlag = smsSendFlag;
    }

    /**
     * get method 
     *
     * @return t_ord_invoice_extend.sms_send_date：短信发送时间
     */
    public Date getSmsSendDate() {
        return smsSendDate;
    }

    /**
     * set method 
     *
     * @param smsSendDate  短信发送时间
     */
    public void setSmsSendDate(Date smsSendDate) {
        this.smsSendDate = smsSendDate;
    }

    /**
     * get method 
     *
     * @return t_ord_invoice_extend.sms_send_content：短信发送内容
     */
    public String getSmsSendContent() {
        return smsSendContent;
    }

    /**
     * set method 
     *
     * @param smsSendContent  短信发送内容
     */
    public void setSmsSendContent(String smsSendContent) {
        this.smsSendContent = smsSendContent == null ? null : smsSendContent.trim();
    }

    /**
     * get method 
     *
     * @return t_ord_invoice_extend.create_user：创建人
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * set method 
     *
     * @param createUser  创建人
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * get method 
     *
     * @return t_ord_invoice_extend.create_time：创建时间
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * set method 
     *
     * @param createTime  创建时间
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * get method 
     *
     * @return t_ord_invoice_extend.update_user：修改人
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * set method 
     *
     * @param updateUser  修改人
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * get method 
     *
     * @return t_ord_invoice_extend.update_time：修改时间
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * set method 
     *
     * @param updateTime  修改时间
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * get method 
     *
     * @return t_ord_invoice_extend.invalid：是否红冲作废(0否 1:已红冲)
     */
    public Integer getInvalid() {
        return invalid;
    }

    /**
     * set method 
     *
     * @param invalid  是否红冲作废(0否 1:已红冲)
     */
    public void setInvalid(Integer invalid) {
        this.invalid = invalid;
    }

    /**
     * get method 
     *
     * @return t_ord_invoice_extend.device_code：税控设备编号
     */
    public String getDeviceCode() {
        return deviceCode;
    }

    /**
     * set method 
     *
     * @param deviceCode  税控设备编号
     */
    public void setDeviceCode(String deviceCode) {
        this.deviceCode = deviceCode == null ? null : deviceCode.trim();
    }

    /**
     * get method 
     *
     * @return t_ord_invoice_extend.remark：备注
     */
    public String getRemark() {
        return remark;
    }

    /**
     * set method 
     *
     * @param remark  备注
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * get method 
     *
     * @return t_ord_invoice_extend.invoice_flowing_code：发票流水号
     */
    public String getInvoiceFlowingCode() {
        return invoiceFlowingCode;
    }

    /**
     * set method 
     *
     * @param invoiceFlowingCode  发票流水号
     */
    public void setInvoiceFlowingCode(String invoiceFlowingCode) {
        this.invoiceFlowingCode = invoiceFlowingCode == null ? null : invoiceFlowingCode.trim();
    }

    /**
     * get method 
     *
     * @return t_ord_invoice_extend.invoice_amount：发票金额（含税：元）
     */
    public BigDecimal getInvoiceAmount() {
        return invoiceAmount;
    }

    /**
     * set method 
     *
     * @param invoiceAmount  发票金额（含税：元）
     */
    public void setInvoiceAmount(BigDecimal invoiceAmount) {
        this.invoiceAmount = invoiceAmount;
    }

    /**
     * get method 
     *
     * @return t_ord_invoice_extend.billing_type：开票类型（0=蓝字发票，1=红字发票）
     */
    public Integer getBillingType() {
        return billingType;
    }

    /**
     * set method 
     *
     * @param billingType  开票类型（0=蓝字发票，1=红字发票）
     */
    public void setBillingType(Integer billingType) {
        this.billingType = billingType;
    }

    /**
     *
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", invoiceExtendId=").append(invoiceExtendId);
        sb.append(", invoiceId=").append(invoiceId);
        sb.append(", invoiceCode=").append(invoiceCode);
        sb.append(", invoiceNumber=").append(invoiceNumber);
        sb.append(", billingTime=").append(billingTime);
        sb.append(", invoceCiphertext=").append(invoceCiphertext);
        sb.append(", validateCode=").append(validateCode);
        sb.append(", xzm=").append(xzm);
        sb.append(", qrcode=").append(qrcode);
        sb.append(", returnCode=").append(returnCode);
        sb.append(", returnMsg=").append(returnMsg);
        sb.append(", smsSendFlag=").append(smsSendFlag);
        sb.append(", smsSendDate=").append(smsSendDate);
        sb.append(", smsSendContent=").append(smsSendContent);
        sb.append(", createUser=").append(createUser);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateUser=").append(updateUser);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", invalid=").append(invalid);
        sb.append(", deviceCode=").append(deviceCode);
        sb.append(", remark=").append(remark);
        sb.append(", invoiceFlowingCode=").append(invoiceFlowingCode);
        sb.append(", invoiceAmount=").append(invoiceAmount);
        sb.append(", billingType=").append(billingType);
        sb.append("]");
        return sb.toString();
    }
}