package com.foresee.ftcsp.order.auto.model;

import java.io.Serializable;
import java.util.Date;

public class OrdOrderUserDep implements Serializable {
    /**
     * 主键
     * 表 : t_ord_order_user_dep
     * 对应字段 : id
     */
    private Long id;

    /**
     * 机构ID
     * 表 : t_ord_order_user_dep
     * 对应字段 : ins_id
     */
    private String insId;

    /**
     * 来源ID(上级部门或总金财或省金财)
     * 表 : t_ord_order_user_dep
     * 对应字段 : src_id
     */
    private String srcId;

    /**
     * 业务code
     * 表 : t_ord_order_user_dep
     * 对应字段 : business_type
     */
    private String businessType;

    /**
     * 拥有者ID
     * 表 : t_ord_order_user_dep
     * 对应字段 : owner_id
     */
    private String ownerId;

    /**
     * 订单ID
     * 表 : t_ord_order_user_dep
     * 对应字段 : order_id
     */
    private Long orderId;

    /**
     * 分配类型 1表示用户，部门分类由业务自己定义，一达通：5省金财、10服务商
     * 表 : t_ord_order_user_dep
     * 对应字段 : distri_type
     */
    private Short distriType;

    /**
     * 创建人
     * 表 : t_ord_order_user_dep
     * 对应字段 : create_user
     */
    private String createUser;

    /**
     * 创建时间
     * 表 : t_ord_order_user_dep
     * 对应字段 : create_time
     */
    private Date createTime;

    /**
     * 更新人
     * 表 : t_ord_order_user_dep
     * 对应字段 : update_user
     */
    private String updateUser;

    /**
     * 更新时间
     * 表 : t_ord_order_user_dep
     * 对应字段 : update_time
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_ord_order_user_dep
     *
     * @MBG Generated Thu Nov 30 10:06:58 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * get method 
     *
     * @return t_ord_order_user_dep.id：主键
     */
    public Long getId() {
        return id;
    }

    /**
     * set method 
     *
     * @param id  主键
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * get method 
     *
     * @return t_ord_order_user_dep.ins_id：机构ID
     */
    public String getInsId() {
        return insId;
    }

    /**
     * set method 
     *
     * @param insId  机构ID
     */
    public void setInsId(String insId) {
        this.insId = insId == null ? null : insId.trim();
    }

    /**
     * get method 
     *
     * @return t_ord_order_user_dep.src_id：来源ID(上级部门或总金财或省金财)
     */
    public String getSrcId() {
        return srcId;
    }

    /**
     * set method 
     *
     * @param srcId  来源ID(上级部门或总金财或省金财)
     */
    public void setSrcId(String srcId) {
        this.srcId = srcId == null ? null : srcId.trim();
    }

    /**
     * get method 
     *
     * @return t_ord_order_user_dep.business_type：业务code
     */
    public String getBusinessType() {
        return businessType;
    }

    /**
     * set method 
     *
     * @param businessType  业务code
     */
    public void setBusinessType(String businessType) {
        this.businessType = businessType == null ? null : businessType.trim();
    }

    /**
     * get method 
     *
     * @return t_ord_order_user_dep.owner_id：拥有者ID
     */
    public String getOwnerId() {
        return ownerId;
    }

    /**
     * set method 
     *
     * @param ownerId  拥有者ID
     */
    public void setOwnerId(String ownerId) {
        this.ownerId = ownerId == null ? null : ownerId.trim();
    }

    /**
     * get method 
     *
     * @return t_ord_order_user_dep.order_id：订单ID
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * set method 
     *
     * @param orderId  订单ID
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * get method 
     *
     * @return t_ord_order_user_dep.distri_type：分配类型 1表示用户，部门分类由业务自己定义，一达通：5省金财、10服务商
     */
    public Short getDistriType() {
        return distriType;
    }

    /**
     * set method 
     *
     * @param distriType  分配类型 1表示用户，部门分类由业务自己定义，一达通：5省金财、10服务商
     */
    public void setDistriType(Short distriType) {
        this.distriType = distriType;
    }

    /**
     * get method 
     *
     * @return t_ord_order_user_dep.create_user：创建人
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * set method 
     *
     * @param createUser  创建人
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * get method 
     *
     * @return t_ord_order_user_dep.create_time：创建时间
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * set method 
     *
     * @param createTime  创建时间
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * get method 
     *
     * @return t_ord_order_user_dep.update_user：更新人
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * set method 
     *
     * @param updateUser  更新人
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * get method 
     *
     * @return t_ord_order_user_dep.update_time：更新时间
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * set method 
     *
     * @param updateTime  更新时间
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     *
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", insId=").append(insId);
        sb.append(", srcId=").append(srcId);
        sb.append(", businessType=").append(businessType);
        sb.append(", ownerId=").append(ownerId);
        sb.append(", orderId=").append(orderId);
        sb.append(", distriType=").append(distriType);
        sb.append(", createUser=").append(createUser);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateUser=").append(updateUser);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }
}