package com.foresee.ftcsp.order.auto.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class OrdOrderContract implements Serializable {
    /**
     * 合同ID
     * 表 : t_ord_order_contract
     * 对应字段 : contract_id
     */
    private String contractId;

    /**
     * 合同编码
     * 表 : t_ord_order_contract
     * 对应字段 : contract_code
     */
    private String contractCode;

    /**
     * 合同签订日期
     * 表 : t_ord_order_contract
     * 对应字段 : contract_sign_time
     */
    private Date contractSignTime;

    /**
     * 拥有者ID 如订单ID
     * 表 : t_ord_order_contract
     * 对应字段 : owner_id
     */
    private Long ownerId;

    /**
     * 拥有者类型 1-订单
     * 表 : t_ord_order_contract
     * 对应字段 : owner_type
     */
    private Integer ownerType;

    /**
     * 首期预付费
     * 表 : t_ord_order_contract
     * 对应字段 : down_payment
     */
    private BigDecimal downPayment;

    /**
     * 平台服务费
     * 表 : t_ord_order_contract
     * 对应字段 : platform_service_payment
     */
    private BigDecimal platformServicePayment;

    /**
     * 服务开始日期
     * 表 : t_ord_order_contract
     * 对应字段 : contract_service_start_time
     */
    private Date contractServiceStartTime;

    /**
     * 服务结束日期
     * 表 : t_ord_order_contract
     * 对应字段 : contract_service_end_time
     */
    private Date contractServiceEndTime;

    /**
     * 计费开始日期
     * 表 : t_ord_order_contract
     * 对应字段 : contract_charging_start_time
     */
    private Date contractChargingStartTime;

    /**
     * 计费结束日期
     * 表 : t_ord_order_contract
     * 对应字段 : contract_charging_end_time
     */
    private Date contractChargingEndTime;

    /**
     * 备注
     * 表 : t_ord_order_contract
     * 对应字段 : remark
     */
    private String remark;

    /**
     * 创建时间
     * 表 : t_ord_order_contract
     * 对应字段 : create_time
     */
    private Date createTime;

    /**
     * 更新人
     * 表 : t_ord_order_contract
     * 对应字段 : update_user
     */
    private String updateUser;

    /**
     * 创建人
     * 表 : t_ord_order_contract
     * 对应字段 : create_user
     */
    private String createUser;

    /**
     * 更新时间
     * 表 : t_ord_order_contract
     * 对应字段 : update_time
     */
    private Date updateTime;

    /**
     * 乙方
     * 表 : t_ord_order_contract
     * 对应字段 : part_b
     */
    private String partB;

    /**
     * 甲方
     * 表 : t_ord_order_contract
     * 对应字段 : part_a
     */
    private String partA;

    /**
     * 丙方
     * 表 : t_ord_order_contract
     * 对应字段 : part_c
     */
    private String partC;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_ord_order_contract
     *
     * @MBG Generated Tue Jan 30 11:44:40 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * get method 
     *
     * @return t_ord_order_contract.contract_id：合同ID
     */
    public String getContractId() {
        return contractId;
    }

    /**
     * set method 
     *
     * @param contractId  合同ID
     */
    public void setContractId(String contractId) {
        this.contractId = contractId == null ? null : contractId.trim();
    }

    /**
     * get method 
     *
     * @return t_ord_order_contract.contract_code：合同编码
     */
    public String getContractCode() {
        return contractCode;
    }

    /**
     * set method 
     *
     * @param contractCode  合同编码
     */
    public void setContractCode(String contractCode) {
        this.contractCode = contractCode == null ? null : contractCode.trim();
    }

    /**
     * get method 
     *
     * @return t_ord_order_contract.contract_sign_time：合同签订日期
     */
    public Date getContractSignTime() {
        return contractSignTime;
    }

    /**
     * set method 
     *
     * @param contractSignTime  合同签订日期
     */
    public void setContractSignTime(Date contractSignTime) {
        this.contractSignTime = contractSignTime;
    }

    /**
     * get method 
     *
     * @return t_ord_order_contract.owner_id：拥有者ID 如订单ID
     */
    public Long getOwnerId() {
        return ownerId;
    }

    /**
     * set method 
     *
     * @param ownerId  拥有者ID 如订单ID
     */
    public void setOwnerId(Long ownerId) {
        this.ownerId = ownerId;
    }

    /**
     * get method 
     *
     * @return t_ord_order_contract.owner_type：拥有者类型 1-订单
     */
    public Integer getOwnerType() {
        return ownerType;
    }

    /**
     * set method 
     *
     * @param ownerType  拥有者类型 1-订单
     */
    public void setOwnerType(Integer ownerType) {
        this.ownerType = ownerType;
    }

    /**
     * get method 
     *
     * @return t_ord_order_contract.down_payment：首期预付费
     */
    public BigDecimal getDownPayment() {
        return downPayment;
    }

    /**
     * set method 
     *
     * @param downPayment  首期预付费
     */
    public void setDownPayment(BigDecimal downPayment) {
        this.downPayment = downPayment;
    }

    /**
     * get method 
     *
     * @return t_ord_order_contract.platform_service_payment：平台服务费
     */
    public BigDecimal getPlatformServicePayment() {
        return platformServicePayment;
    }

    /**
     * set method 
     *
     * @param platformServicePayment  平台服务费
     */
    public void setPlatformServicePayment(BigDecimal platformServicePayment) {
        this.platformServicePayment = platformServicePayment;
    }

    /**
     * get method 
     *
     * @return t_ord_order_contract.contract_service_start_time：服务开始日期
     */
    public Date getContractServiceStartTime() {
        return contractServiceStartTime;
    }

    /**
     * set method 
     *
     * @param contractServiceStartTime  服务开始日期
     */
    public void setContractServiceStartTime(Date contractServiceStartTime) {
        this.contractServiceStartTime = contractServiceStartTime;
    }

    /**
     * get method 
     *
     * @return t_ord_order_contract.contract_service_end_time：服务结束日期
     */
    public Date getContractServiceEndTime() {
        return contractServiceEndTime;
    }

    /**
     * set method 
     *
     * @param contractServiceEndTime  服务结束日期
     */
    public void setContractServiceEndTime(Date contractServiceEndTime) {
        this.contractServiceEndTime = contractServiceEndTime;
    }

    /**
     * get method 
     *
     * @return t_ord_order_contract.contract_charging_start_time：计费开始日期
     */
    public Date getContractChargingStartTime() {
        return contractChargingStartTime;
    }

    /**
     * set method 
     *
     * @param contractChargingStartTime  计费开始日期
     */
    public void setContractChargingStartTime(Date contractChargingStartTime) {
        this.contractChargingStartTime = contractChargingStartTime;
    }

    /**
     * get method 
     *
     * @return t_ord_order_contract.contract_charging_end_time：计费结束日期
     */
    public Date getContractChargingEndTime() {
        return contractChargingEndTime;
    }

    /**
     * set method 
     *
     * @param contractChargingEndTime  计费结束日期
     */
    public void setContractChargingEndTime(Date contractChargingEndTime) {
        this.contractChargingEndTime = contractChargingEndTime;
    }

    /**
     * get method 
     *
     * @return t_ord_order_contract.remark：备注
     */
    public String getRemark() {
        return remark;
    }

    /**
     * set method 
     *
     * @param remark  备注
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * get method 
     *
     * @return t_ord_order_contract.create_time：创建时间
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * set method 
     *
     * @param createTime  创建时间
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * get method 
     *
     * @return t_ord_order_contract.update_user：更新人
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * set method 
     *
     * @param updateUser  更新人
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * get method 
     *
     * @return t_ord_order_contract.create_user：创建人
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * set method 
     *
     * @param createUser  创建人
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * get method 
     *
     * @return t_ord_order_contract.update_time：更新时间
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * set method 
     *
     * @param updateTime  更新时间
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * get method 
     *
     * @return t_ord_order_contract.part_b：乙方
     */
    public String getPartB() {
        return partB;
    }

    /**
     * set method 
     *
     * @param partB  乙方
     */
    public void setPartB(String partB) {
        this.partB = partB == null ? null : partB.trim();
    }

    /**
     * get method 
     *
     * @return t_ord_order_contract.part_a：甲方
     */
    public String getPartA() {
        return partA;
    }

    /**
     * set method 
     *
     * @param partA  甲方
     */
    public void setPartA(String partA) {
        this.partA = partA == null ? null : partA.trim();
    }

    /**
     * get method 
     *
     * @return t_ord_order_contract.part_c：丙方
     */
    public String getPartC() {
        return partC;
    }

    /**
     * set method 
     *
     * @param partC  丙方
     */
    public void setPartC(String partC) {
        this.partC = partC == null ? null : partC.trim();
    }

    /**
     *
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", contractId=").append(contractId);
        sb.append(", contractCode=").append(contractCode);
        sb.append(", contractSignTime=").append(contractSignTime);
        sb.append(", ownerId=").append(ownerId);
        sb.append(", ownerType=").append(ownerType);
        sb.append(", downPayment=").append(downPayment);
        sb.append(", platformServicePayment=").append(platformServicePayment);
        sb.append(", contractServiceStartTime=").append(contractServiceStartTime);
        sb.append(", contractServiceEndTime=").append(contractServiceEndTime);
        sb.append(", contractChargingStartTime=").append(contractChargingStartTime);
        sb.append(", contractChargingEndTime=").append(contractChargingEndTime);
        sb.append(", remark=").append(remark);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateUser=").append(updateUser);
        sb.append(", createUser=").append(createUser);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", partB=").append(partB);
        sb.append(", partA=").append(partA);
        sb.append(", partC=").append(partC);
        sb.append("]");
        return sb.toString();
    }
}