package com.foresee.ftcsp.order.auto.model;

import java.io.Serializable;
import java.util.Date;

public class OrdOrderExtend implements Serializable {
    /**
     * 无业务意义主键
     * 表 : t_ord_order_extend
     * 对应字段 : order_extend_id
     */
    private Long orderExtendId;

    /**
     * 订单主键：订单id
     * 表 : t_ord_order_extend
     * 对应字段 : order_id
     */
    private Long orderId;

    /**
     * 订单所对应的代账中心
     * 表 : t_ord_order_extend
     * 对应字段 : dep_id
     */
    private String depId;

    /**
     * 会计主管ID
     * 表 : t_ord_order_extend
     * 对应字段 : accounting_supervisor_id
     */
    private String accountingSupervisorId;

    /**
     * 会计助理ID
     * 表 : t_ord_order_extend
     * 对应字段 : accounting_assistant_id
     */
    private String accountingAssistantId;

    /**
     * 代理时间起
     * 表 : t_ord_order_extend
     * 对应字段 : agent_begin_time
     */
    private Date agentBeginTime;

    /**
     * 代理时间止
     * 表 : t_ord_order_extend
     * 对应字段 : agent_end_time
     */
    private Date agentEndTime;

    /**
     * 描述
     * 表 : t_ord_order_extend
     * 对应字段 : remark
     */
    private String remark;

    /**
     * 创建人
     * 表 : t_ord_order_extend
     * 对应字段 : create_user
     */
    private String createUser;

    /**
     * 创建时间
     * 表 : t_ord_order_extend
     * 对应字段 : create_time
     */
    private Date createTime;

    /**
     * 修改人
     * 表 : t_ord_order_extend
     * 对应字段 : update_user
     */
    private String updateUser;

    /**
     * 修改日期
     * 表 : t_ord_order_extend
     * 对应字段 : update_time
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_ord_order_extend
     *
     * @MBG Generated Thu Aug 17 10:48:48 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * get method 
     *
     * @return t_ord_order_extend.order_extend_id：无业务意义主键
     */
    public Long getOrderExtendId() {
        return orderExtendId;
    }

    /**
     * set method 
     *
     * @param orderExtendId  无业务意义主键
     */
    public void setOrderExtendId(Long orderExtendId) {
        this.orderExtendId = orderExtendId;
    }

    /**
     * get method 
     *
     * @return t_ord_order_extend.order_id：订单主键：订单id
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * set method 
     *
     * @param orderId  订单主键：订单id
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * get method 
     *
     * @return t_ord_order_extend.dep_id：订单所对应的代账中心
     */
    public String getDepId() {
        return depId;
    }

    /**
     * set method 
     *
     * @param depId  订单所对应的代账中心
     */
    public void setDepId(String depId) {
        this.depId = depId == null ? null : depId.trim();
    }

    /**
     * get method 
     *
     * @return t_ord_order_extend.accounting_supervisor_id：会计主管ID
     */
    public String getAccountingSupervisorId() {
        return accountingSupervisorId;
    }

    /**
     * set method 
     *
     * @param accountingSupervisorId  会计主管ID
     */
    public void setAccountingSupervisorId(String accountingSupervisorId) {
        this.accountingSupervisorId = accountingSupervisorId == null ? null : accountingSupervisorId.trim();
    }

    /**
     * get method 
     *
     * @return t_ord_order_extend.accounting_assistant_id：会计助理ID
     */
    public String getAccountingAssistantId() {
        return accountingAssistantId;
    }

    /**
     * set method 
     *
     * @param accountingAssistantId  会计助理ID
     */
    public void setAccountingAssistantId(String accountingAssistantId) {
        this.accountingAssistantId = accountingAssistantId == null ? null : accountingAssistantId.trim();
    }

    /**
     * get method 
     *
     * @return t_ord_order_extend.agent_begin_time：代理时间起
     */
    public Date getAgentBeginTime() {
        return agentBeginTime;
    }

    /**
     * set method 
     *
     * @param agentBeginTime  代理时间起
     */
    public void setAgentBeginTime(Date agentBeginTime) {
        this.agentBeginTime = agentBeginTime;
    }

    /**
     * get method 
     *
     * @return t_ord_order_extend.agent_end_time：代理时间止
     */
    public Date getAgentEndTime() {
        return agentEndTime;
    }

    /**
     * set method 
     *
     * @param agentEndTime  代理时间止
     */
    public void setAgentEndTime(Date agentEndTime) {
        this.agentEndTime = agentEndTime;
    }

    /**
     * get method 
     *
     * @return t_ord_order_extend.remark：描述
     */
    public String getRemark() {
        return remark;
    }

    /**
     * set method 
     *
     * @param remark  描述
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * get method 
     *
     * @return t_ord_order_extend.create_user：创建人
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * set method 
     *
     * @param createUser  创建人
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * get method 
     *
     * @return t_ord_order_extend.create_time：创建时间
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * set method 
     *
     * @param createTime  创建时间
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * get method 
     *
     * @return t_ord_order_extend.update_user：修改人
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * set method 
     *
     * @param updateUser  修改人
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * get method 
     *
     * @return t_ord_order_extend.update_time：修改日期
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * set method 
     *
     * @param updateTime  修改日期
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     *
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", orderExtendId=").append(orderExtendId);
        sb.append(", orderId=").append(orderId);
        sb.append(", depId=").append(depId);
        sb.append(", accountingSupervisorId=").append(accountingSupervisorId);
        sb.append(", accountingAssistantId=").append(accountingAssistantId);
        sb.append(", agentBeginTime=").append(agentBeginTime);
        sb.append(", agentEndTime=").append(agentEndTime);
        sb.append(", remark=").append(remark);
        sb.append(", createUser=").append(createUser);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateUser=").append(updateUser);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }
}