package com.foresee.ftcsp.order.auto.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class OrdReimburse implements Serializable {
    /**
     * 主键，退款id
     * 表 : t_ord_reimburse
     * 对应字段 : reimburse_id
     */
    private Long reimburseId;

    /**
     * 账单id
     * 表 : t_ord_reimburse
     * 对应字段 : bill_id
     */
    private Long billId;

    /**
     * 退款金额
     * 表 : t_ord_reimburse
     * 对应字段 : reimburse_amount
     */
    private BigDecimal reimburseAmount;

    /**
     * 退款方式(0支付宝，1-微信，2-银联,3现金）
     * 表 : t_ord_reimburse
     * 对应字段 : reimburse_way
     */
    private Integer reimburseWay;

    /**
     * 退款账号
     * 表 : t_ord_reimburse
     * 对应字段 : reimburse_account
     */
    private String reimburseAccount;

    /**
     * 退款类型（0 全额 1 部分）
     * 表 : t_ord_reimburse
     * 对应字段 : reimburse_type
     */
    private Integer reimburseType;

    /**
     * 退款时间
     * 表 : t_ord_reimburse
     * 对应字段 : reimburse_time
     */
    private Date reimburseTime;

    /**
     * 退款人
     * 表 : t_ord_reimburse
     * 对应字段 : reimburse_person
     */
    private String reimbursePerson;

    /**
     * 退款人联系方式
     * 表 : t_ord_reimburse
     * 对应字段 : reimburse_phone
     */
    private String reimbursePhone;

    /**
     * 创建人
     * 表 : t_ord_reimburse
     * 对应字段 : create_user
     */
    private String createUser;

    /**
     * 创建时间
     * 表 : t_ord_reimburse
     * 对应字段 : create_time
     */
    private Date createTime;

    /**
     * 修改人
     * 表 : t_ord_reimburse
     * 对应字段 : update_user
     */
    private String updateUser;

    /**
     * 修改日期
     * 表 : t_ord_reimburse
     * 对应字段 : update_time
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_ord_reimburse
     *
     * @MBG Generated Thu Aug 17 10:48:48 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * get method 
     *
     * @return t_ord_reimburse.reimburse_id：主键，退款id
     */
    public Long getReimburseId() {
        return reimburseId;
    }

    /**
     * set method 
     *
     * @param reimburseId  主键，退款id
     */
    public void setReimburseId(Long reimburseId) {
        this.reimburseId = reimburseId;
    }

    /**
     * get method 
     *
     * @return t_ord_reimburse.bill_id：账单id
     */
    public Long getBillId() {
        return billId;
    }

    /**
     * set method 
     *
     * @param billId  账单id
     */
    public void setBillId(Long billId) {
        this.billId = billId;
    }

    /**
     * get method 
     *
     * @return t_ord_reimburse.reimburse_amount：退款金额
     */
    public BigDecimal getReimburseAmount() {
        return reimburseAmount;
    }

    /**
     * set method 
     *
     * @param reimburseAmount  退款金额
     */
    public void setReimburseAmount(BigDecimal reimburseAmount) {
        this.reimburseAmount = reimburseAmount;
    }

    /**
     * get method 
     *
     * @return t_ord_reimburse.reimburse_way：退款方式(0支付宝，1-微信，2-银联,3现金）
     */
    public Integer getReimburseWay() {
        return reimburseWay;
    }

    /**
     * set method 
     *
     * @param reimburseWay  退款方式(0支付宝，1-微信，2-银联,3现金）
     */
    public void setReimburseWay(Integer reimburseWay) {
        this.reimburseWay = reimburseWay;
    }

    /**
     * get method 
     *
     * @return t_ord_reimburse.reimburse_account：退款账号
     */
    public String getReimburseAccount() {
        return reimburseAccount;
    }

    /**
     * set method 
     *
     * @param reimburseAccount  退款账号
     */
    public void setReimburseAccount(String reimburseAccount) {
        this.reimburseAccount = reimburseAccount == null ? null : reimburseAccount.trim();
    }

    /**
     * get method 
     *
     * @return t_ord_reimburse.reimburse_type：退款类型（0 全额 1 部分）
     */
    public Integer getReimburseType() {
        return reimburseType;
    }

    /**
     * set method 
     *
     * @param reimburseType  退款类型（0 全额 1 部分）
     */
    public void setReimburseType(Integer reimburseType) {
        this.reimburseType = reimburseType;
    }

    /**
     * get method 
     *
     * @return t_ord_reimburse.reimburse_time：退款时间
     */
    public Date getReimburseTime() {
        return reimburseTime;
    }

    /**
     * set method 
     *
     * @param reimburseTime  退款时间
     */
    public void setReimburseTime(Date reimburseTime) {
        this.reimburseTime = reimburseTime;
    }

    /**
     * get method 
     *
     * @return t_ord_reimburse.reimburse_person：退款人
     */
    public String getReimbursePerson() {
        return reimbursePerson;
    }

    /**
     * set method 
     *
     * @param reimbursePerson  退款人
     */
    public void setReimbursePerson(String reimbursePerson) {
        this.reimbursePerson = reimbursePerson == null ? null : reimbursePerson.trim();
    }

    /**
     * get method 
     *
     * @return t_ord_reimburse.reimburse_phone：退款人联系方式
     */
    public String getReimbursePhone() {
        return reimbursePhone;
    }

    /**
     * set method 
     *
     * @param reimbursePhone  退款人联系方式
     */
    public void setReimbursePhone(String reimbursePhone) {
        this.reimbursePhone = reimbursePhone == null ? null : reimbursePhone.trim();
    }

    /**
     * get method 
     *
     * @return t_ord_reimburse.create_user：创建人
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * set method 
     *
     * @param createUser  创建人
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * get method 
     *
     * @return t_ord_reimburse.create_time：创建时间
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * set method 
     *
     * @param createTime  创建时间
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * get method 
     *
     * @return t_ord_reimburse.update_user：修改人
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * set method 
     *
     * @param updateUser  修改人
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * get method 
     *
     * @return t_ord_reimburse.update_time：修改日期
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * set method 
     *
     * @param updateTime  修改日期
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     *
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", reimburseId=").append(reimburseId);
        sb.append(", billId=").append(billId);
        sb.append(", reimburseAmount=").append(reimburseAmount);
        sb.append(", reimburseWay=").append(reimburseWay);
        sb.append(", reimburseAccount=").append(reimburseAccount);
        sb.append(", reimburseType=").append(reimburseType);
        sb.append(", reimburseTime=").append(reimburseTime);
        sb.append(", reimbursePerson=").append(reimbursePerson);
        sb.append(", reimbursePhone=").append(reimbursePhone);
        sb.append(", createUser=").append(createUser);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateUser=").append(updateUser);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }
}